---
- name: Install the Grafana instance
  kubernetes.core.k8s:
    state: present
    template: "grafana.yaml.j2"

- name: Wait for Grafana instance to deploy
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: "{{ prometheus_namespace }}"
    name: grafana-deployment
    wait: true
    wait_condition:
      type: Available
      status: True
      
#  Creating Grafana route

- name: Get automation controller route name
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: "{{ ansible_namespace }}"
  register: automationcontroller_route

- name: Set fact of domain
  ansible.builtin.set_fact:
    domain: "{{ automationcontroller_route.resources[0].status.ingress[0].routerCanonicalHostname | regex_search('router-default.(.+)', '\\1') | first }}"

#  Exposing Grafana service

- name: Expose grafana-operated service
  kubernetes.core.k8s:
    state: present
    template: "grafana-operated-route.yaml.j2"
