---
- name: Create the bearer token secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: bearertoken
        namespace: "{{ prometheus_namespace }}"
      data:
        secret: "{{ token_result.json.token | b64encode }}"
      type: Opaque

- name: Create the bearer token secret grafana
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ grafana_name }}"
        namespace: "{{ grafana_namespace }}"
      data:
        GF_SECURITY_ADMIN_PASSWORD: '.data.GF_SECURITY_ADMIN_PASSWORD'
        GF_SECURITY_ADMIN_USER: '.data.GF_SECURITY_ADMIN_USER'
      type: Opaque
